### ISSUE TITLE
Does this also optimise single function packages?

### ISSUE THREAD

**Issue by abemedia** [kyle-johnson/rollup-plugin-optimize-lodash-imports#427]
Lots of packages opt for single function lodash packages e.g. `lodash.isempty`, `lodash.clonedeep` etc.
Does this package also optimise these to ensure we dedupe to always use the same lodash function across all dependencies?

**Comment by kyle-johnson** [comment]
No, that is out of scope. I suspect something like that is best handled with a lint rule that prohibits specifically importing lodash. 🤔
