### ISSUE TITLE
[esbuild] could not interpret ts syntax

### ISSUE THREAD

**Issue by ldu1020** [kyle-johnson/rollup-plugin-optimize-lodash-imports#428]
There was a problem with using esbuild plugins in ts package among those modules. esbuild was an issue that could not interpret ts syntax,

I would like to write the loader value among the return values of onLoad in consideration of ts.

```ts
  build.onLoad({ filter: /.(js|ts|jsx|tsx)$/ }, (args) => {
   ...
            return {
              ...
              loader: 'ts' // or path.parse(args.path).ext.slice(1),
             }
   })
 ```

**Comment by ldu1020** [comment]
In addition, since the acorn currently used internally does not respond to the typecript, it can be done by extending it using the acorn-typescript package.

```ts
const { tsPlugin } = __importStar(require("acorn-typescript"));
const wrappedParse = (code) => acorn.Parser.extend(tsPlugin()).parse(code, { ecmaVersion: "latest", sourceType: "module" });
```

**Comment by kyle-johnson** [comment]
3.0.0 supports this! Thanks so much @ldu1020 for figuring out the hard parts :-)
